spring:
    application:
        name: api
    data:
        mongodb:
            uri: mongodb+srv://RodrigoAraujo:televisaoBoa@cluster0.ouap9.mongodb.net/dbitem?retryWrites=true&w=majority&appName=Cluster0